const root=document.documentElement,intro=document.querySelector('#intro');
if(intro&&root.classList.contains('intro-pending')){let done=false;const close=()=>{if(done)return;done=true;intro.classList.add('is-leaving');try{sessionStorage.setItem('cp-intro-v2','1')}catch(e){}setTimeout(()=>{root.classList.remove('intro-pending');intro.remove()},450)};document.querySelector('#introSkip')?.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()},{once:true});setTimeout(close,1850)}else{root.classList.remove('intro-pending');intro?.remove()}

const reveals=document.querySelectorAll('.reveal');
if('IntersectionObserver'in window){const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.15});reveals.forEach(el=>revealObserver.observe(el))}else reveals.forEach(el=>el.classList.add('is-visible'));

const categoryLinks=[...document.querySelectorAll('.category-nav a')];
const categories=categoryLinks.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);
categoryLinks.forEach(link=>link.addEventListener('click',()=>{categoryLinks.forEach(item=>{item.classList.toggle('active',item===link);item===link?item.setAttribute('aria-current','true'):item.removeAttribute('aria-current')})}));
if('IntersectionObserver'in window){const categoryObserver=new IntersectionObserver(entries=>{const current=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!current)return;categoryLinks.forEach(link=>{const active=link.hash===`#${current.target.id}`;link.classList.toggle('active',active);active?link.setAttribute('aria-current','true'):link.removeAttribute('aria-current');if(active)link.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})})},{rootMargin:'-28% 0px -62%',threshold:[0,.15,.4]});categories.forEach(section=>categoryObserver.observe(section))}
